### ISSUE TITLE
Error starting VeloView 

### ISSUE THREAD

**Issue by Grillen80** [Kitware/VeloView#26]
I've build the VeloView Application without any errors under Linux Xenial 16.04.
While starting the application, the following error occurs and I do not have any possibilties to choose a device. 

_Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named paraview.simple
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/local/lib/veloview-3.1/site-packages/veloview/applogic.py", line 20, in <module>
    import paraview.simple as smp
ImportError: No module named paraview.simple
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vv' is not defined_

Thanks for your help in advance. Kind regards,
Sven

**Comment by Grillen80** [comment]
I fixed the issue with an export of the installed site-packages to the $PYTHONPATH

**Comment by karnikram** [comment]
Hi, 
I'm facing the same issue.

Could you provide me more details about your $PYTHONPATH?
