### ISSUE TITLE
Error opening .pcap in fresh superbuild

### ISSUE THREAD

**Issue by brh5047** [Kitware/VeloView#92]
Recent super build on ubuntu 18.04, everything seemed to make properly:

Error trying to open .pcap file. .pcap reads back fine on regular veloview build. 

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/VeloViewSLAM/VeloView-build/common-superbuild/veloview/build/bin/../lib/site-packages/veloview/applogic.py", line 32, in <module>
    import planefit
  File "/VeloViewSLAM/VeloView-build/common-superbuild/veloview/build/bin/../lib/site-packages/veloview/planefit.py", line 15, in <module>
    import VelodyneHDLPluginPython as vvmod
ImportError: libVelodyneHDLPluginPythonD.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vv' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vv' is not defined

**Comment by gkharish** [comment]
Hello @brh5047 ,
I am facing the same issue. Have you resolved it?
I installed on Ubuntu 18.04 following the instruction given here(I'm interested to get SLAM working)
https://github.com/Kitware/LidarView/blob/master/Documentation/How-To-SLAM-With-Veloview.md

Thanks!
